#include "memtier.h"
#include "internal/object_table.h"
#include "internal/residency_table.h"
#include "internal/path_selector.h"
#include "internal/posix_backend.h"
#include "internal/gds_backend.h"
#include "internal/dram_cache.h"
#include "internal/cuda_utils.h"
#include <cuda_runtime.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <mutex>

const char* memtierResidencyToString(MemTierResidency r){ switch(r){ case MemTierResidency::SSD_ONLY:return "SSD_ONLY"; case MemTierResidency::DRAM_RESIDENT:return "DRAM_RESIDENT"; case MemTierResidency::HBM_RESIDENT:return "HBM_RESIDENT"; case MemTierResidency::DRAM_AND_HBM:return "DRAM_AND_HBM";} return "UNKNOWN"; }
const char* memtierPathToString(MemTierPath p){ switch(p){ case MemTierPath::POSIX_TO_DRAM:return "POSIX_TO_DRAM"; case MemTierPath::DRAM_TO_HBM:return "DRAM_TO_HBM"; case MemTierPath::GDS_TO_HBM:return "GDS_TO_HBM"; case MemTierPath::HYBRID_GDS_AND_DRAM:return "HYBRID_GDS_AND_DRAM";} return "UNKNOWN"; }
namespace { ObjectTable objs; ResidencyTable res; PosixBackend posixb; GdsBackend gds; DramCache cache; RuntimeCapability cap; std::mutex mu; bool managed_mode(){ const char* e=getenv("MEMTIER_ALLOC_MODE"); return e && std::strcmp(e,"managed")==0; } int fill_posix(ObjectEntry& o, cudaStream_t s){ if(posixb.openFile(o)!=0) return -1; void* host=cache.get(o.file_range); bool cached=host!=nullptr; if(!cached){ if(memtier::cuda_utils::allocate_pinned(&host,o.file_range.length)!=0) return -1; auto n=posixb.readToPinnedHost(o,host,o.file_range.length,o.file_range.offset); if(n!=(ssize_t)o.file_range.length){ memtier::cuda_utils::free_pinned(host); return -1;} cache.put(o.file_range,host,o.file_range.length); } o.host_pinned_ptr=host; if(!o.device_ptr && !o.managed_ptr) return -1; void* dst=o.managed_ptr?o.managed_ptr:o.device_ptr; CUDA_CHECK(cudaMemcpyAsync(dst,host,o.file_range.length,cudaMemcpyHostToDevice,s)); if(o.managed_ptr) CUDA_CHECK(cudaMemPrefetchAsync(o.managed_ptr,o.file_range.length,cap.device_id,s)); CUDA_CHECK(cudaStreamSynchronize(s)); o.last_path=cached?MemTierPath::DRAM_TO_HBM:MemTierPath::POSIX_TO_DRAM; o.residency=cached?MemTierResidency::DRAM_AND_HBM:MemTierResidency::DRAM_AND_HBM; o.fill_count++; res.setResidency(o.object_id,o.residency); return 0; } }
int memtierInit(int device_id){ std::lock_guard<std::mutex> l(mu); if(memtier::cuda_utils::set_device(device_id)!=0) return -1; cap.device_id=device_id; cap.gds_available=gds.init(); std::printf("GDS available: %s\nPOSIX fallback available: yes\nCUDA device: %d\n", cap.gds_available?"yes":"no", device_id); return 0; }
int memtierFinalize(){ std::lock_guard<std::mutex> l(mu); gds.finalize(); return 0; }
int memtierMapFile(const char* path, uint64_t off, size_t len, unsigned flags, MemTierHandle* out){ if(!path||!out||len==0) return -1; std::lock_guard<std::mutex> l(mu); ObjectEntry o; o.path=path; o.flags=flags; o.file_range={ObjectTable::fileIdForPath(path),off,len}; int rc=managed_mode()?memtier::cuda_utils::allocate_managed(&o.managed_ptr,len):memtier::cuda_utils::allocate_device(&o.device_ptr,len); if(rc!=0) return -1; o.va={o.managed_ptr?o.managed_ptr:o.device_ptr,len}; int id=objs.insert(o); res.setResidency(id,MemTierResidency::SSD_ONLY); *out={o.va.start,len,off,o.file_range.file_id,id}; std::printf("MemTier map object_id=%d path=%s offset=%llu length=%zu selected_path=%s\n",id,path,(unsigned long long)off,len,"SSD_ONLY"); return 0; }
int memtierPrefetchToGpu(MemTierHandle h, cudaStream_t s){ std::lock_guard<std::mutex> l(mu); ObjectEntry* o=objs.lookupById(h.object_id); if(!o) return -1; MemTierPath p=selectPath(*o,cap); o->last_path=p; std::printf("MemTier prefetch object_id=%d path=%s offset=%llu length=%zu selected_path=%s\n",o->object_id,o->path.c_str(),(unsigned long long)o->file_range.offset,o->file_range.length,memtierPathToString(p)); if(p==MemTierPath::GDS_TO_HBM && cap.gds_available && o->device_ptr){ if(gds.openFile(*o)==0 && gds.registerFile(*o)==0 && gds.registerBuffer(*o,o->device_ptr,o->file_range.length)==0){ auto n=gds.readToGpu(*o,o->device_ptr,o->file_range.length,o->file_range.offset); if(n==(ssize_t)o->file_range.length){ CUDA_CHECK(cudaStreamSynchronize(s)); o->residency=MemTierResidency::HBM_RESIDENT; o->fill_count++; res.setResidency(o->object_id,o->residency); return 0; } } std::fprintf(stderr,"MemTier: GDS path failed, falling back to POSIX for object_id=%d path=%s offset=%llu length=%zu selected_path=%s\n",o->object_id,o->path.c_str(),(unsigned long long)o->file_range.offset,o->file_range.length,memtierPathToString(p)); }
 return fill_posix(*o,s); }
int memtierPrefetchToDram(MemTierHandle h){ std::lock_guard<std::mutex> l(mu); ObjectEntry* o=objs.lookupById(h.object_id); if(!o) return -1; if(posixb.openFile(*o)!=0) return -1; void* host=nullptr; if(memtier::cuda_utils::allocate_pinned(&host,o->file_range.length)!=0) return -1; auto n=posixb.readToPinnedHost(*o,host,o->file_range.length,o->file_range.offset); if(n!=(ssize_t)o->file_range.length){ memtier::cuda_utils::free_pinned(host); return -1;} cache.put(o->file_range,host,o->file_range.length); o->host_pinned_ptr=host; o->residency=MemTierResidency::DRAM_RESIDENT; res.setResidency(o->object_id,o->residency); return 0; }
int memtierEnsureResident(MemTierHandle h, int target, cudaStream_t s){ if(target==(int)MemTierResidency::DRAM_RESIDENT) return memtierPrefetchToDram(h); return memtierPrefetchToGpu(h,s); }
int memtierUnmapFile(MemTierHandle h){ std::lock_guard<std::mutex> l(mu); ObjectEntry* o=objs.lookupById(h.object_id); if(!o) return -1; gds.deregisterBuffer(*o); gds.closeFile(*o); posixb.closeFile(*o); memtier::cuda_utils::free_device(o->device_ptr?o->device_ptr:o->managed_ptr); res.remove(o->object_id); objs.remove(o->object_id); return 0; }
void memtierPrintState(){ std::lock_guard<std::mutex> l(mu); objs.print(); }
MemTierResidency memtierGetResidency(MemTierHandle h){ auto* o=objs.lookupById(h.object_id); return o?o->residency:MemTierResidency::SSD_ONLY; }
MemTierPath memtierGetLastPath(MemTierHandle h){ auto* o=objs.lookupById(h.object_id); return o?o->last_path:MemTierPath::POSIX_TO_DRAM; }
